### ISSUE TITLE
Playlist?

### ISSUE THREAD

**Issue by kaizokupuffball** [deskjet/chiptune2.js#10]
Hi! Nice work. :)
Would be nice too see looping as the one posted before, but i alos would like to load and entire directory into a simple playlist. Will there come an option for this? 

Keep up the good work. :+1

Edit:
Never mind the looping. Got it figured. Just using the onEnded. :)

**Comment by deskjet** [comment]
Thank you for messing with the project.
Did you try to load the next song in your playlist using a onEnded hander? I think that would work just fine, although I didn't try.
Looping works sort of, as you figured out. A "real" looping mode using libopenmpt's looping feature is planned, but there is no timeline.

**Comment by kaizokupuffball** [comment]
Oh, yea, why didnt i think of that. Ill try that for the playlist. Thank
you. :)
7. sep. 2015 12:55 skrev "Simon Gündling" <notifications@github.com>:

**Comment by DanielOaks** [comment]
Might be good to add a little example of queuing a few songs / attaching to the `onEnded` handler. Maybe support for saying "play this file then this file then this file" or something like that?

Could be interesting, later down the track.

**Comment by deskjet** [comment]
Sounds like a good idea to me. Perhaps as part of the demo page.

I'll have some spare time in a few weeks. Maybe i'll look into that.

**Comment by onikienko** [comment]
player.onEnded(function () {
            // call play next song
      });
         
      player.onError(function (e) {
            // call play next song
       });

You can see more here http://keygenmusic.tk/   
It uses chiptune2.js  
Deeply in β   
Will upload sources to github soon

**Comment by DanielOaks** [comment]
Awesome, thanks for linking that site too @onikienko, will definitely need to take a good look through it!
