### ISSUE TITLE
Could not load libopenmpt.js.mem

### ISSUE THREAD

**Issue by magnus-eriksson** [deskjet/chiptune2.js#13]
I don't know if it's me that missed something but now the js-lib tries to load `libopenmpt.js.mem` from the root folder of the site (not where I have the rest of the scripts).

When I tested yesterday I didn't need that file at all?

**Comment by deskjet** [comment]
This is due to using a newer version of Emscripten. See #6 for further explanation and workaround.

**Comment by magnus-eriksson** [comment]
Ah. Perfect... thanks for an awesome lib! :)
