### ISSUE TITLE
Don't check for e.total

### ISSUE THREAD

**Issue by sagamusix** [deskjet/chiptune2.js#14]
Since today, ModArchive's online player is powered by libopenmpt + chiptune2.js! :) (see http://modarchive.org/ - player link can be found on any module page)

However, one problem I initially stumbled upon was that the server-side script serving the module files didn't send a Content-Length header. In Chrome (but not Firefox), this caused the e.total variable of the XMLHttpRequest onload event to be 0, even though the total file size was of course known at this point. So I patched the serving script to send the correct Content-Length along, but this is probably not always possible, so omitting the check for e.total not being 0 might be a good idea.

**Comment by deskjet** [comment]
Check removed. I don't see why chrome doesn't set the total length at this point, but I guess we just have to live with that.

**Comment by onikienko** [comment]
It looks like server-side issue, not Chrome.

**Comment by sagamusix** [comment]
It's not a server-side "issue" if the server doesn't sent Content-Length, because that header field is optional by the standard. Anyway, as deskjet implemented an appropriate fix, there's no need to discuss this further.
