### ISSUE TITLE
Update libopenmpt

### ISSUE THREAD

**Issue by sagamusix** [deskjet/chiptune2.js#20]
Many people seem to take their libopenmpt.js copy right from this repository, which is a bit unfortunate since it's several versions behind the current release. Updating to the latest version (and maybe encouraging people in the readme to compile their own, up-to-date version) would be appreciated.

**Comment by deskjet** [comment]
I updated libopenmpt.js to the latest release of libopenmpt and added a paragraph to the Readme. Hope it helps.

**Comment by sagamusix** [comment]
Perfect ;)

**Comment by sagamusix** [comment]
Since we have automated builds of the latest test versions now, it might also make sense to mention this link in the manual for everyone who cannot or doesn't want to use emscripten: https://builds.openmpt.org/builds/auto/libopenmpt/bin.js/

**Comment by deskjet** [comment]
Done

**Comment by sagamusix** [comment]
Thanks. :) By the way, the link should be the exact one that I posted, not leading to the 0.3.0-pre4 folder, since that is just the latest test version. If the API changes during development of 0.3.0, the next version would be 0.3.0-pre5, and once the first official release of 0.3.0 happens, the -pre* suffix will just disappear completely. In either case, there would be no more new versions in the -pre4 folder, once again leading to people downloading outdated builds. :)

**Comment by deskjet** [comment]
Fixed, thanks for the heads up.

**Comment by sagamusix** [comment]
Sorry to bother again, but manx just updated the directory structure and the *most recent* builds are now to be found here instead: https://builds.openmpt.org/builds/auto/libopenmpt/dev.js/

**Comment by deskjet** [comment]
Got it :thumbsup:
