### ISSUE TITLE
M03 Format Support

### ISSUE THREAD

**Issue by RyanBram** [deskjet/chiptune2.js#22]
Hi, Developers.

I tried your github demo and your website, and so far everything play nicely. The only thing I am missing is M03 Format support.
Based on your libopenmpt github version, it is the first version which has native support of M03 without relying on Closed Source UN4SEEN MO3 decoder. So it should be able to play MO3 files.

Thank you for your attention

**Comment by deskjet** [comment]
You are right: MO3 is not supported. It needs integrated mp3 and vorbis decoders which are currently not included in the emscripten build.

They could be enabled in libopenmpt's build system and I'm fairly positive that it would compile and work.

BTW: don't look at my libopenmpt repo, it is heavily outdated. Chiptune.js uses a newer version and you are encouraged to do your own build of the latest libopenmpt release. The official libopenmpt releases support the emscripten toolchain out of the box now.

**Comment by RyanBram** [comment]
Many thanks for the informations. :smile: 

On 20th August Manx from OpenMPT provided a precompiled libopenmpt.js using buildbot . He said MO3 with Vorbis decoder is supported. But after replacing the libopenmpt from your Github master with one from OpenMPT official build I still cannot make MO3 works.
Is there any configuration or code that need to be modified from your chiptune.js? I am not very good about Javascript, so any help will be really appreciated.

Best regards,
RyanBram

**Comment by deskjet** [comment]
I managed to build a version with the builtin MO3 decoder (vorbis only). You can download it [here](https://github.com/deskjet/chiptune2.js/files/429716/bin.zip).
[This](https://gist.github.com/deskjet/1c80096e1a57448210c5d4f49f218835) is the make configuration I used.

**Comment by RyanBram** [comment]
:tada: What a great news :tada: 
Thank you so much for your help.
I think this can be marked as solved.
Really appreciate to what you have done now.

Best regards, :smile: 
RyanBram
