### ISSUE TITLE
Javascript and PhoneGap Build

### ISSUE THREAD

**Issue by yoheiniimi** [deskjet/chiptune2.js#38]
Hello!
I am trying to make chiptune2.js work with Javascript and Adobe PhoneGap Build.
https://build.phonegap.com

Android apk is playing the sound fine, but iOS ipa won't.
The handers[] is empty so it seems there is no error...

It works on Chrome and Safari so the onclick action is working.

===

ChiptuneJsPlayer.prototype.load = function(input, callback) {
    xhr.onload = function(e) {
      if (xhr.status === 200) {
        ***It doesn't reach here***
        return callback(xhr.response); // no error
      } else {
        **It reaches here and the xhr value was like this...**
        xhr.readyState = 4
        xhr.status = 0
        xhr.statusText = blank
        player.fireEvent('onError', {type: 'onxhr'});
}

**Comment by yoheiniimi** [comment]
I saw some blog says that for a local file we only get 0 for status so I put these two

if (xhr.readyState === 4 &&xhr.status === 200) {
}
if (xhr.readyState === 4 &&xhr.status === 0) {
}

instead of this
if (xhr.status === 200) {

and now it's working in ipa app but it make whole app very slow...actually stops the app.

**Comment by deskjet** [comment]
I don't know much about iOS/Safari. However checking `readySate` in the `onload` function seems redundant as `onload` implies that the request is done.

Also this doesn't look right:
```
if (xhr.readyState === 4 &&xhr.status === 200) {
}
if (xhr.readyState === 4 &&xhr.status === 0) {
}
```

The code will call the succes handler no matter what. Try 
```
if (xhr.status === 0  || xhr.status === 200) {
```
But I wouln't want to rely on `0` meaning success. As the same value is also used for incomplete requests.

**Comment by yoheiniimi** [comment]
Thank you four your advise!

I have tried some plugins,

https://github.com/Telerik-Verified-Plugins/WKWebView
This seems doesn't change anything (status is still 0, and app gets super slow).

https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix
This will stop the app when it's initializing ...trying to find why.

https://github.com/oracle/cordova-plugin-wkwebview-file-xhr
https://github.com/apache/cordova-plugin-wkwebview-engine
These two gives a Build error...now working to find the reason.

**Comment by yoheiniimi** [comment]
Solved!
This is now working for me, and my app is running fast.
https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix

Couldn't build before because I was missing some of these in config.xml.
    <feature name="CDVWKWebViewEngine">
        <param name="ios-package" value="CDVWKWebViewEngine" />
    </feature>
    <plugin name="cordova-plugin-file" spec="^4.3.3" />
    <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
    <plugin name="cordova-plugin-console" spec="~1.0.7" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <plugin name="cordova-plugin-wkwebview-engine" spec="^1.1.3" />
    <plugin name="cordova-plugin-wkwebviewxhrfix" spec="https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix" />

Aslo I've changed 'onload' to 'onloadend' to make sure the data is loaded.

Thank you for your help!

**Comment by deskjet** [comment]
I'm glad you got it working :)
