### ISSUE TITLE
Upgrading libopenmpt breaks tempo/pitch sliders

### ISSUE THREAD

**Issue by christiancodes** [deskjet/chiptune2.js#40]
Hi there! Encountering this error – can be seen on the demo page.
```
chiptune2.js:85 Uncaught TypeError: libopenmpt.ccall is not a function
    at ChiptuneJsPlayer.module_ctl_set (chiptune2.js:85)
```

I guess libopenmpt changed their API for this: 
```
ChiptuneJsPlayer.prototype.module_ctl_set = function(ctl, value) {
  return libopenmpt.ccall('openmpt_module_ctl_set', 'number', ['number', 'string', 'string'], [this.currentPlayingNode.modulePtr, ctl, value]) === 1;
}
```

**Comment by deskjet** [comment]
Sorry about that. Looks like an incompatibility with newer Emscripten versions. Something appears to be wrong with metadata, too. I think I can push a fix later today.

@sagamusix Would you mind adding `-s EXTRA_EXPORTED_RUNTIME_METHODS="['ccall']` to the LDFLAGS in official builds?

**Comment by sagamusix** [comment]
In general, we'd like to keep the list of default exported functions 
small and just let people override the defaults if they need more. I'm 
pretty sure there are ways to use openmpt_module_ctl_set without 
requiring `ccall`.

Small example how I'm doing it on modarchive.org:

```
function asciiToStack(str) {
   var stackStr = stackAlloc(str.length + 1);
   writeAsciiToMemory(str, stackStr);
   return stackStr;
}

var stack = stackSave();
libopenmpt._openmpt_module_ctl_set(processNode.modulePtr, 
asciiToStack('render.resampler.emulate_amiga'), asciiToStack('1'));
libopenmpt._openmpt_module_ctl_set(processNode.modulePtr, 
asciiToStack('render.resampler.emulate_amiga_type'), asciiToStack('a1200'));
stackRestore(stack);
```

**Comment by sagamusix** [comment]
In general, we'd like to keep the list of default exported functions 
small and just let people override the defaults if they need more. I'm 
pretty sure there are ways to use openmpt_module_ctl_set without 
requiring `ccall`.

Small example how I'm doing it on modarchive.org:

```
function asciiToStack(str) {
   var stackStr = stackAlloc(str.length + 1);
   writeAsciiToMemory(str, stackStr);
   return stackStr;
}

var stack = stackSave();
libopenmpt._openmpt_module_ctl_set(processNode.modulePtr, 
asciiToStack('render.resampler.emulate_amiga'), asciiToStack('1'));
libopenmpt._openmpt_module_ctl_set(processNode.modulePtr, 
asciiToStack('render.resampler.emulate_amiga_type'), asciiToStack('a1200'));
stackRestore(stack);
```

**Comment by deskjet** [comment]
Thanks @sagamusix, I'll consider it. For now I pushed a custom build with `ccall` exported.

**Comment by christiancodes** [comment]
Thanks! This fixes the issue on my end.
