### ISSUE TITLE
Export to WAV?

### ISSUE THREAD

**Issue by birdie-github** [deskjet/chiptune2.js#43]
Subject.

Why? E.g. I want to get a WAV file, convert it to mp3/m4a and set it as a ringtone on my phone.

**Comment by deskjet** [comment]
It think it can be done but not as part of this project. It's really only meant to be a little player.

If you just want to convert a few tunes to mp3 for yourself I recommend getting OpenMPT (https://openmpt.org/) and export them from there in your format of choice or use ffmpeg compiled with `--enable-libopenmpt` (the same lib used here) if you prefer a CLI tool.

If you want to build a browser-based tool anyway (could be a fun project). I'd recommend skipping the Web Audio stuff entirely and directly convert the raw PCM output from libopenmpt into WAV (or something else). I believe https://github.com/ffmpegwasm/ffmpeg.wasm should be able to do that. Altough ffmpeg is massive overkill just to go from PCM to WAV. WAV is only a thin wrapper for raw PCM with some metadata.
