### ISSUE TITLE
Looping songs

### ISSUE THREAD

**Issue by DanielOaks** [deskjet/chiptune2.js#5]
One thing that'd be nice is being able to loop a song seamlessly. If you reset the position to 0 at the end of the song it resets, but there is a noticable few-second pause before it starts up again.

**Comment by magnus-eriksson** [comment]
I second this. Actually, I would love to have the same loop functionallity as in chiptune.js.
I have a bunch of one pattern chips that triggers new channels/sounds when the pattern repeats and with this lib the mods sounds awesome but I miss the majority of the song. :(

Any chance this will be implemented?

**Comment by DanielOaks** [comment]
I'll look into this, hopefully it shouldn't be too difficult. The library already has support for it, just need to hopefully expose it nicely.

**Comment by magnus-eriksson** [comment]
You guys are rockstars... or chipstars... :)
