### ISSUE TITLE
libopenmpt-0.2.4764-beta10 doesn't play.

### ISSUE THREAD

**Issue by luckcolors** [deskjet/chiptune2.js#6]
Hello i'm having problems using the latest version of libopenmpt-0.2.4764-beta10
I've tried compiling the windows and linux version of src http://lib.openmpt.org/libopenmpt/#sec_download both of them gives me the same compiled files.

This is the log in firefox dev tools:

Successfully compiled asm.js code (total compilation time 3548ms; unable to cache asm.js in synchronous scripts; try loading asm.js via <script async> or createElement('script'); 1 functions compiled slowly: Pu:7:119032 (776ms)) libopenmpt.js
NS_ERROR_DOM_BAD_URI: Access to restricted URI denied libopenmpt.js:1:0
26 libopenmpt.js:1:2439 <<<<< here is when i try to play a song.
26 libopenmpt.js:1:2518
TypeError: abortDecorators is undefined libopenmpt.js:24:39233

I hope you can help me :)

**Comment by deskjet** [comment]
Recent versions of Emscripten output a separate memory initialization file (.js.mem), which is loaded by libopenmpt.js asynchronously.
It is expected to be in the same directory with index.html (look at the networking tab in dev tools). If you want to put it somewhere else you need to edit the path in `libopenmpt.js` manually. There is no option in Emscripten to do so (yet?).
Just open `libopenmpt.js` in a editor (nano works for me). Search for `memoryInitializer=` and change the path as you like. I prefixed `js/` so .js.mem and .js files can be in the same directory.

**Comment by luckcolors** [comment]
Ok it works! Thanks :)
